# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 70
  - name: News
    url: post
    weight: 80
  - name: People
    url: people
    weight: 90
  - name: Events
    url: event
    weight: 110
  - name: Publications
    url: publication
    weight: 100

  - name: My Story
    url: author/jang
    weight: 10

  - name: Projects
    url: 
    weight: 20
  - parent: Projects
    name: Dino Adventure
    url: projects/dino
    weight: 23
  - parent: Projects
    name: Bill Gates
    url: projects/billgates
    weight: 22
  - parent: Projects
    name: Space Escape(진행중)
    url: projects/space
    weight: 21

  - name: Practices
    url: 
    weight: 30
  - parent: Practices
    name: 3D Survival
    url: practies/survival
    weight: 33
  - parent: Practices
    name: Interaction
    url: practies/interaction
    weight: 32
  - parent: Practices
    name: Tile Bania
    url: practies/tile
    weight: 31

  - name: Planning
    url: 
    weight: 40
  - parent: Planning
    name: Cave
    url: planning/cave
    weight: 43
  - parent: Planning
    name: Debuff
    url: planning/debuff
    weight: 42
  - parent: Planning
    name: Gacha
    url: planning/gacha
    weight: 41

  - name: Other
    url: 
    weight: 50
  - parent: Other
    name: Cave
    url: other/cave
    weight: 51
  - parent: Other
    name: Debuff
    url: other/debuff
    weight: 52

  - name: Contact
    url: contact
    weight: 60