# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 70
  - name: News
    url: post
    weight: 80
  - name: People
    url: people
    weight: 40
  - name: Events
    url: event
    weight: 50
  - name: Publications
    url: publication
    weight: 60

  - name: Contact
    url: contact
    weight: 10

  - name: Projects
    url: 
    weight: 20
  - parent: Projects
    name: Dino Adventure
    url: projects/dino
    weight: 21
  - parent: Projects
    name: Bill Gates
    url: projects/billgates
    weight: 22
  - parent: Projects
    name: Space Escape(진행중)
    url: projects/space
    weight: 23

  - name: Practices
    url: 
    weight: 30
  - parent: Practices
    name: 3D Survival
    url: practies/survival
    weight: 31
  - parent: Practices
    name: 
    url: practies/
    weight: 32
  - parent: Practices
    name: 
    url: practies/
    weight: 33
